name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install pytest

      - name: Doctests
        run: python -m doctest -v hello_world.py

      - name: Unit Tests
        run: python -m pytest tests

      - name: Run Script
        run: ./hello_world.py
